export const AUTH_ACTION = {
    AUTH_REQ_LOGIN: 'AUTH_REQ_LOGIN',
    AUTH_SUCCESS_LOGIN: 'AUTH_SUCCESS_LOGIN',
    AUTH_FAILED_LOGIN: 'AUTH_FAILED_LOGIN',
    AUTH_CLEAR_LOGIN: 'AUTH_CLEAR_LOGIN',

    AUTH_LOGIN_TYPE: 'AUTH_LOGIN_TYPE',

    AUTH_LOADING_SESSION: 'AUTH_LOADING_SESSION',
    AUTH_SUCCESS_SESSION: 'AUTH_SUCCESS_SESSION',

}